In [1]:
import pandas as pd
import numpy as np
import csv

In [2]:
df = pd.read_excel (r'preprocess_securites.xlsx', sheet_name='HY')

In [3]:
df["OAS"].head()

0    304
1    273
2    284
3    294
4    268
Name: OAS, dtype: int64

In [4]:
df.describe()

,OAS,Excess Return % 1-mo (Treasury),Excess Return % 1-mo (Agg),Excess Return % 3-mo (Treasury),Excess Return % 3-mo (Agg),Excess Return % 6-mo (Treasury),Excess Return % 6-mo (Agg),Excess Return % 9-mo (Treasury),Excess Return % 9-mo (Agg),Excess Return % 12-mo (Treasury),Excess Return % 12-mo (Agg),Excess Return % 24-mo (Treasury),Excess Return % 24-mo (Agg),Excess Return % 36-mo (Treasury),Excess Return % 36-mo (Agg),Quadrant
count,280.000000,280.000000,280.000000,278.000000,278.000000,275.000000,275.000000,272.000000,272.000000,269.000000,269.000000,257.000000,257.000000,245.000000,245.000000,279.00000
mean,555.267857,0.177493,0.112788,0.550633,0.357559,1.222200,0.828601,1.868890,1.280967,2.521253,1.751629,5.310354,3.865666,8.251518,6.142775,2.55914
std,262.262139,2.955461,2.583599,5.912487,5.177686,8.968352,7.861320,10.754642,9.462071,12.203688,10.774519,16.413970,14.737665,17.765014,16.326793,1.08418
min,246.000000,-16.532000,-13.937600,-38.039000,-32.579400,-44.358000,-37.326100,-38.080000,-32.650000,-44.540000,-37.002500,-49.760000,-39.798800,-43.755000,-34.598000,1.00000
25%,376.250000,-0.732500,-0.757125,-1.125500,-1.384900,-2.270500,-2.450650,-3.464000,-3.707625,-3.630000,-4.262500,-3.557000,-3.792500,-1.486000,-1.887400,2.00000
50%,489.000000,0.355000,0.289600,1.252000,1.028450,1.855000,1.569000,2.778500,1.824300,3.143000,1.815900,7.507000,6.191700,10.256000,9.012400,3.00000
75%,658.250000,1.432500,1.261475,3.189000,2.932350,5.243500,4.318550,6.379750,5.682475,8.668000,7.557900,13.077000,11.535400,19.181000,16.495900,3.00000
max,1978.000000,12.580000,10.987900,23.830000,19.986800,36.201000,30.480900,42.789000,36.189500,48.274000,41.204100,59.279000,50.163900,58.142000,48.745000,4.00000

In [10]:
# OAS Outlier Adjustment
q1 = df["OAS"].quantile(0.25)
q3 = df["OAS"].quantile(0.75)

iqr = q3 - q1

lower_bound = q1 -(1.5 * iqr) 
upper_bound = q3 +(1.5 * iqr)

print(lower_bound)

for x in df["OAS"]:
    if x > upper_bound:
         x = upper_bound
    df.replace(to_replace = x, 
                 value =x)
    print(x)

-46.75
304
273
284
294
268
267
271
259
259
299
290
296
300
287
283
298
318
337
338
520
595
652
544
566
560
521
519
476
475
487
466
490
507
513
491
476
487
508
575
588
616
617
626
643
677
779
906
916
787
770
818
806
768
816
827
805
1018
961
839
824
789
819
708
688
728
874
971
962
1036
1059
883
890
829
838
772
644
679
613
566
546
549
471
448
418
405
434
441
391
428
410
401
406
382
357
306
309
330
283
352
418
413
385
330
366
354
361
367
371
342
337
313
304
312
335
345
349
344
329
320
289
272
282
285
274
246
298
419
454
419
436
574
591
693
765
816
682
648
730
795
830
1081.25
1081.25
1081.25
1081.25
1081.25
1081.25
1081.25
1081.25
1081.25
1033
903
886
770
739
741
622
641
657
571
549
683
699
646
680
616
581
610
531
499
469
471
469
502
535
549
718
826
694
763
709
651
588
589
593
682
629
605
587
564
554
556
526
488
491
480
448
457
514
466
473
479
433
424
400
421
381
377
371
367
353
404
384
440
430
467
504
526
446
482
459
458
500
536
570
662
590
640
695
777
775
705
621
597
621
569
510
497
491
467
422
400
374
392
381
374
377
361
385
356
351
361
363
329
347
372
346
363
371
346
349
328
381
429
533
437
392
405
373
459
407
393
413
402
415
402
360
403
506
877
763

In [12]:
# OAS Outlier Adjustment
q1 = df["Excess Return % 1-mo (Treasury)"].quantile(0.25)
q3 = df["Excess Return % 1-mo (Treasury)"].quantile(0.75)

iqr = q3 - q1

lower_bound = q1 -(1.5 * iqr) 
upper_bound = q3 +(1.5 * iqr)

print(lower_bound)

for x in df["Excess Return % 1-mo (Treasury)"]:
    if x > upper_bound:
         x = upper_bound
    df.replace(to_replace = x, 
                 value =x)
    if x < lower_bound:
         x = lower_bound
    df.replace(to_replace = x, 
                 value =x)
        
    print(x)

-3.98
0.682
1.608
-0.344
-0.044
1.431
0.617
0.13
0.843
0.465
-0.907
0.707
0.069
0.175
0.729
0.802
0.118
-0.052
-0.151
0.361
-3.98
-2.652
-1.863
4.68
-0.355
0.95
1.848
0.677
1.61
0.356
-0.163
0.457
-0.98
-1.076
-0.432
1.674
1.201
0.042
-0.58
-3.248
0.472
-1.511
0.285
-0.01
-0.194
-1.379
-3.81
-3.98
0.587
4.68
0.43
-2.694
-0.569
1.409
-3.034
-0.557
-0.173
-3.98
1.308
4.68
-0.006
0.009
-2.351
4.507
-0.431
-1.658
-3.98
-3.98
0.836
-3.98
-0.283
4.68
-0.812
3.342
-0.151
2.797
4.68
-1.253
3.186
1.978
0.965
-0.081
3.418
1.3
1.553
0.915
-1.208
-0.231
2.229
-1.206
1.092
0.453
-0.093
1.223
1.237
2.283
0.687
-0.501
2.208
-2.412
-2.671
0.744
1.419
2.811
-1.083
0.126
-0.038
-0.011
0.063
1.777
0.601
1.345
0.855
-0.103
-0.628
-0.155
0.203
0.456
0.964
0.627
1.787
1.183
-0.193
0.144
0.811
1.535
-1.705
-3.98
-0.536
1.851
-0.154
-3.98
0.148
-3.98
-2.496
-1.271
4.68
1.558
-3.331
-2.168
-0.82
-3.98
-3.98
-3.98
4.68
4.68
-3.129
1.553
4.68
4.68
3.525
4.68
1.23
4.68
1.644
-0.389
4.68
0.082
-0.267
3.807
1.364
-3.98
-0.275
2.678
-1.304
2.779
2.253
-0.501
3.437
1.866
1.518
0.485
0.456
-0.887
-0.826
-0.433
-3.98
-3.98
4.68
-2.693
1.83
2.372
2.776
0.542
-0.115
-2.255
2.255
1.244
1.183
1.519
0.988
0.283
1.868
1.962
-0.036
0.884
1.232
0.775
-1.579
1.871
-0.103
0.131
1.999
0.692
1.437
-0.425
1.754
0.608
0.295
0.12
1.001
-1.083
0.651
-1.644
0.266
-1.395
-1.328
-1.362
3.511
-1.098
1.406
0.294
-0.96
-1.213
-1.8
-3.467
3.116
-1.903
-2.382
-3.411
-0.178
4.229
4.045
0.833
-0.543
2.417
2.714
0.529
0.909
1.517
2.001
1.146
1.211
-0.221
0.563
0.482
0.35
0.865
-0.696
1.499
0.477
-0.012
0.203
1.654
-0.563
-1.232
1.304
-0.706
0.354
1.356
0.087
1.153
-1.622
-1.649
-3.824
4.122
1.77
-0.258
1.377
-2.698
1.61
0.648
-1.33
0.692
-0.05
0.474
2.134
-1.258
-3.064
-3.98
3.56

In [6]:
''''
def mod_outlier(df):
    df1 = df.copy()
    df = df._get_numeric_data()


    q1 = df.quantile(0.25)
    q3 = df.quantile(0.75)

    iqr = q3 - q1

    lower_bound = q1 -(1.5 * iqr) 
    upper_bound = q3 +(1.5 * iqr)

    for col in df.columns:
        for i in range(0,len(df[col])):
            if df[col][i] < lower_bound[col]:            
                df[col][i] = lower_bound[col]

            if df[col][i] > upper_bound[col]:            
                df[col][i] = upper_bound[col]    

            for col in df.columns:
                df1[col] = df[col]    
            return(df1)

#def mod_outlier(df):
df1 = df.copy()
df = df._get_numeric_data()


q1 = df.quantile(0.25)
q3 = df.quantile(0.75)

iqr = q3 - q1

lower_bound = q1 -(1.5 * iqr) 
upper_bound = q3 +(1.5 * iqr)

for col in df.columns:
        for i in range(0,len(df[col])):
            if df[col][i] < lower_bound[col]:            
                df[col][i] = lower_bound[col]

            if df[col][i] > upper_bound[col]:            
                df[col][i] = upper_bound[col]    

            for col in df.columns:
                df1[col] = df[col]    
            return(df1)
            
''''

SyntaxError: EOL while scanning string literal (<ipython-input-6-7827cf9319b5>, line 52)

In [ ]:
df = mod_outlier(df)

In [ ]:
df.head()

In [ ]:
df["OAS"].describe()