In [1]:
import numpy as np
import pandas as pd

In [2]:
! pip install --user researchpy

Requirement already satisfied: researchpy in /Users/valazeinali/.local/lib/python3.7/site-packages (0.2.2)
Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.7/site-packages (from researchpy) (1.0.1)
Requirement already satisfied: statsmodels in /opt/anaconda3/lib/python3.7/site-packages (from researchpy) (0.11.0)
Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.7/site-packages (from researchpy) (1.18.1)
Requirement already satisfied: scipy in /opt/anaconda3/lib/python3.7/site-packages (from researchpy) (1.4.1)
Requirement already satisfied: pytz>=2017.2 in /opt/anaconda3/lib/python3.7/site-packages (from pandas->researchpy) (2019.3)
Requirement already satisfied: python-dateutil>=2.6.1 in /opt/anaconda3/lib/python3.7/site-packages (from pandas->researchpy) (2.8.1)
Requirement already satisfied: patsy>=0.5 in /opt/anaconda3/lib/python3.7/site-packages (from statsmodels->researchpy) (0.5.1)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.7/site-packages (from python-dateutil>=2.6.1->pandas->researchpy) (1.14.0)

In [3]:
import researchpy # for t-test stuff!

In [4]:
df = pd.read_csv('minmax_OAS_with_Returns_Final_NO_Outliers_MBS.csv')

In [5]:
df.head()

,Date,OAS,Excess Return % 1-mo (Treasury),Excess Return % 1-mo (Agg),Excess Return % 3-mo (Treasury),Excess Return % 3-mo (Agg),Excess Return % 6-mo (Treasury),Excess Return % 6-mo (Agg),Excess Return % 9-mo (Treasury),Excess Return % 9-mo (Agg),Excess Return % 12-mo (Treasury),Excess Return % 12-mo (Agg),Excess Return % 24-mo (Treasury),Excess Return % 24-mo (Agg),Excess Return % 36-mo (Treasury),Excess Return % 36-mo (Agg),Quadrant
0,1997-01-31 00:00:00,0.350365,0.717929,0.725832,0.630776,0.712547,0.745522,0.677576,0.708116,0.592760,0.694897,0.492488,0.570117,0.253638,0.747463,0.551875,4.0
1,1997-02-28 00:00:00,0.313869,0.637829,0.558983,0.601489,0.639215,0.562434,0.410301,0.594846,0.455540,0.589623,0.389947,0.540783,0.202642,0.541103,0.473883,4.0
2,1997-03-31 00:00:00,0.372263,0.375000,0.589971,0.562439,0.615111,0.556375,0.547829,0.525178,0.408284,0.592410,0.436515,0.586204,0.353999,0.529601,0.467643,4.0
3,1997-04-30 00:00:00,0.335766,0.661608,0.586265,0.667873,0.547397,0.599052,0.451645,0.602666,0.365778,0.632933,0.420977,0.645439,0.352820,0.409844,0.422184,4.0
4,1997-05-31 00:00:00,0.328467,0.562735,0.513109,0.470997,0.240147,0.496839,0.336672,0.507642,0.286514,0.609563,0.413176,0.607589,0.350575,0.398342,0.441813,4.0

In [6]:
df = df.drop(columns=[#"Total Return % 1-mo-LOC", "Agg Returns" ,
"Excess Return % 1-mo (Treasury)", "Excess Return % 1-mo (Agg)"], axis = 0) # get rid of these useless columns

In [7]:
df.describe()

,OAS,Excess Return % 3-mo (Treasury),Excess Return % 3-mo (Agg),Excess Return % 6-mo (Treasury),Excess Return % 6-mo (Agg),Excess Return % 9-mo (Treasury),Excess Return % 9-mo (Agg),Excess Return % 12-mo (Treasury),Excess Return % 12-mo (Agg),Excess Return % 24-mo (Treasury),Excess Return % 24-mo (Agg),Excess Return % 36-mo (Treasury),Excess Return % 36-mo (Agg),Quadrant
count,279.000000,278.000000,278.000000,275.000000,275.000000,272.000000,272.000000,269.000000,269.000000,257.000000,257.000000,245.000000,245.000000,279.00000
mean,0.501295,0.493999,0.497352,0.489545,0.495918,0.503700,0.504949,0.512186,0.511790,0.495789,0.445458,0.497647,0.458988,2.55914
std,0.201425,0.207990,0.210104,0.218887,0.209323,0.219842,0.208194,0.221212,0.200958,0.224305,0.213694,0.242868,0.201318,1.08418
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.00000
25%,0.343066,0.375000,0.375000,0.375000,0.375000,0.375000,0.375000,0.375000,0.375000,0.375000,0.292076,0.375000,0.326409,2.00000
50%,0.467153,0.511023,0.511976,0.501054,0.512001,0.509064,0.532947,0.510077,0.536752,0.502933,0.461649,0.466678,0.450613,3.00000
75%,0.605839,0.625000,0.625000,0.625000,0.625000,0.625000,0.625000,0.625000,0.625000,0.625000,0.575246,0.625000,0.595845,3.00000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,4.00000

# drop outliers that we have identified as 0 and 1s (1 is > upper fence, 0 is < lower fence)

In [8]:
# Getting rid of outliers below. When we ran the script to label outliers, the script
# would label a number an outlier a 1 if it was above the Upper fence and would label
# it a 0 if it was an outlier below the lower fence.
# This script replaces all outliers as "NaN"

df["OAS"] = df["OAS"].replace([0],["NaN"])
df["OAS"] = df["OAS"].replace([1],["Nan"])

df = df.dropna()

df['OAS'] = pd.to_numeric(df['OAS'],errors='coerce') # converting back to float64 

df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 245 entries, 0 to 244
Data columns (total 15 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Date                              245 non-null    object
 1   OAS                               234 non-null    float64
 2   Excess Return % 3-mo (Treasury)   245 non-null    float64
 3   Excess Return % 3-mo (Agg)        245 non-null    float64
 4   Excess Return % 6-mo (Treasury)   245 non-null    float64
 5   Excess Return % 6-mo (Agg)        245 non-null    float64
 6   Excess Return % 9-mo (Treasury)   245 non-null    float64
 7   Excess Return % 9-mo (Agg)        245 non-null    float64
 8   Excess Return % 12-mo (Treasury)  245 non-null    float64
 9   Excess Return % 12-mo (Agg)       245 non-null    float64
 10  Excess Return % 24-mo (Treasury)  245 non-null    float64
 11  Excess Return % 24-mo (Agg)       245 non-null    float64
 12  Excess Return % 36-mo (Treasury)  245 non-null    float64
 13  Excess Return % 36-mo (Agg)       245 non-null    float64
 14  Quadrant                          245 non-null    float64
dtypes: float64(14), object(1)
memory usage: 30.6+ KB

# Now lets select all OAS levels and their coresponding excess returns that are above the 75th percentile (top 25%)

In [9]:
# Select * 
# From OAS
# Where OAS >= 75th percentile
## SQL version above ## 
highspread = df["OAS"].quantile(.75) # every data point over the 85th percentile
print(highspread)

# pandas version of the SQL function 
df = df[(df['OAS'] > highspread)]

0.6040145985

In [10]:
df.describe()

,OAS,Excess Return % 3-mo (Treasury),Excess Return % 3-mo (Agg),Excess Return % 6-mo (Treasury),Excess Return % 6-mo (Agg),Excess Return % 9-mo (Treasury),Excess Return % 9-mo (Agg),Excess Return % 12-mo (Treasury),Excess Return % 12-mo (Agg),Excess Return % 24-mo (Treasury),Excess Return % 24-mo (Agg),Excess Return % 36-mo (Treasury),Excess Return % 36-mo (Agg),Quadrant
count,59.000000,59.000000,59.000000,59.000000,59.000000,59.000000,59.000000,59.000000,59.000000,59.000000,59.000000,59.000000,59.000000,59.000000
mean,0.747618,0.479049,0.529232,0.504554,0.550619,0.491156,0.570696,0.507072,0.591016,0.526237,0.484175,0.583539,0.431933,2.677966
std,0.099597,0.266575,0.200418,0.251137,0.221568,0.229170,0.205943,0.251059,0.233415,0.215156,0.235384,0.211724,0.189848,1.089775
min,0.605839,0.000000,0.013125,0.000000,0.000000,0.000000,0.105918,0.000000,0.000000,0.000000,0.000000,0.013701,0.000000,1.000000
25%,0.649635,0.317076,0.414572,0.331138,0.455691,0.374941,0.469252,0.355596,0.475688,0.410579,0.331186,0.431326,0.298411,2.000000
50%,0.744526,0.508095,0.556464,0.535037,0.530049,0.480391,0.562285,0.528302,0.604230,0.532646,0.462929,0.543809,0.390085,3.000000
75%,0.806569,0.659738,0.657013,0.676106,0.674471,0.638448,0.674094,0.682033,0.686710,0.634936,0.639872,0.718369,0.588263,4.000000
max,0.978102,1.000000,0.971814,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.998482,1.000000,0.924476,4.000000

In [11]:
des, res = researchpy.ttest(df['OAS'], df['Excess Return % 3-mo (Treasury)'])

des, res

(                          Variable      N      Mean        SD        SE  \
 0                              OAS   59.0  0.747618  0.099597  0.012966
 1  Excess Return % 3-mo (Treasury)   59.0  0.479049  0.266575  0.034705
 2                         combined  118.0  0.613334  0.241519  0.022234

    95% Conf.  Interval
 0   0.721663  0.773574
 1   0.409579  0.548519
 2   0.569301  0.657366  ,
                                   Independent t-test   results
 0  Difference (OAS - Excess Return % 3-mo (Treasu...    0.2686
 1                              Degrees of freedom =   116.0000
 2                                               t =     7.2492
 3                           Two side test p value =     0.0000
 4                          Difference < 0 p value =     1.0000
 5                          Difference > 0 p value =     0.0000
 6                                       Cohen's d =     1.3347
 7                                       Hedge's g =     1.3260
 8                                   Glass's delta =     2.6966
 9                                               r =     0.5584)

In [12]:
des, res = researchpy.ttest(df['OAS'], df['Excess Return % 3-mo (Agg)'])

des, res

(                     Variable      N      Mean        SD        SE  95% Conf.  \
 0                         OAS   59.0  0.747618  0.099597  0.012966   0.721663
 1  Excess Return % 3-mo (Agg)   59.0  0.529232  0.200418  0.026092   0.477003
 2                    combined  118.0  0.638425  0.191975  0.017673   0.603425

    Interval
 0  0.773574
 1  0.581462
 2  0.673425  ,
                                  Independent t-test   results
 0  Difference (OAS - Excess Return % 3-mo (Agg)) =     0.2184
 1                             Degrees of freedom =   116.0000
 2                                              t =     7.4953
 3                          Two side test p value =     0.0000
 4                         Difference < 0 p value =     1.0000
 5                         Difference > 0 p value =     0.0000
 6                                      Cohen's d =     1.3800
 7                                      Hedge's g =     1.3711
 8                                  Glass's delta =     2.1927
 9                                              r =     0.5712)

In [13]:
des, res = researchpy.ttest(df['OAS'], df['Excess Return % 6-mo (Treasury)'])

des, res

(                          Variable      N      Mean        SD        SE  \
 0                              OAS   59.0  0.747618  0.099597  0.012966
 1  Excess Return % 6-mo (Treasury)   59.0  0.504554  0.251137  0.032695
 2                         combined  118.0  0.626086  0.226007  0.020806

    95% Conf.  Interval
 0   0.721663  0.773574
 1   0.439108  0.570001
 2   0.584882  0.667291  ,
                                   Independent t-test   results
 0  Difference (OAS - Excess Return % 6-mo (Treasu...    0.2431
 1                              Degrees of freedom =   116.0000
 2                                               t =     6.9106
 3                           Two side test p value =     0.0000
 4                          Difference < 0 p value =     1.0000
 5                          Difference > 0 p value =     0.0000
 6                                       Cohen's d =     1.2723
 7                                       Hedge's g =     1.2641
 8                                   Glass's delta =     2.4405
 9                                               r =     0.5400)

In [14]:
des, res = researchpy.ttest(df['OAS'], df['Excess Return % 6-mo (Agg)'])

des, res

(                     Variable      N      Mean        SD        SE  95% Conf.  \
 0                         OAS   59.0  0.747618  0.099597  0.012966   0.721663
 1  Excess Return % 6-mo (Agg)   59.0  0.550619  0.221568  0.028846   0.492878
 2                    combined  118.0  0.649119  0.197583  0.018189   0.613096

    Interval
 0  0.773574
 1  0.608360
 2  0.685141  ,
                                  Independent t-test   results
 0  Difference (OAS - Excess Return % 6-mo (Agg)) =     0.1970
 1                             Degrees of freedom =   116.0000
 2                                              t =     6.2291
 3                          Two side test p value =     0.0000
 4                         Difference < 0 p value =     1.0000
 5                         Difference > 0 p value =     0.0000
 6                                      Cohen's d =     1.1469
 7                                      Hedge's g =     1.1394
 8                                  Glass's delta =     1.9780
 9                                              r =     0.5007)

In [15]:
des, res = researchpy.ttest(df['OAS'], df['Excess Return % 9-mo (Treasury)'])

des, res

(                          Variable      N      Mean        SD        SE  \
 0                              OAS   59.0  0.747618  0.099597  0.012966
 1  Excess Return % 9-mo (Treasury)   59.0  0.491156  0.229170  0.029835
 2                         combined  118.0  0.619387  0.218028  0.020071

    95% Conf.  Interval
 0   0.721663  0.773574
 1   0.431434  0.550878
 2   0.579637  0.659137  ,
                                   Independent t-test   results
 0  Difference (OAS - Excess Return % 9-mo (Treasu...    0.2565
 1                              Degrees of freedom =   116.0000
 2                                               t =     7.8836
 3                           Two side test p value =     0.0000
 4                          Difference < 0 p value =     1.0000
 5                          Difference > 0 p value =     0.0000
 6                                       Cohen's d =     1.4515
 7                                       Hedge's g =     1.4421
 8                                   Glass's delta =     2.5750
 9                                               r =     0.5906)

In [16]:
des, res = researchpy.ttest(df['OAS'], df['Excess Return % 9-mo (Agg)'])

des, res

(                     Variable      N      Mean        SD        SE  95% Conf.  \
 0                         OAS   59.0  0.747618  0.099597  0.012966   0.721663
 1  Excess Return % 9-mo (Agg)   59.0  0.570696  0.205943  0.026811   0.517027
 2                    combined  118.0  0.659157  0.183942  0.016933   0.625622

    Interval
 0  0.773574
 1  0.624365
 2  0.692693  ,
                                  Independent t-test   results
 0  Difference (OAS - Excess Return % 9-mo (Agg)) =     0.1769
 1                             Degrees of freedom =   116.0000
 2                                              t =     5.9405
 3                          Two side test p value =     0.0000
 4                         Difference < 0 p value =     1.0000
 5                         Difference > 0 p value =     0.0000
 6                                      Cohen's d =     1.0937
 7                                      Hedge's g =     1.0867
 8                                  Glass's delta =     1.7764
 9                                              r =     0.4830)

In [17]:
des, res = researchpy.ttest(df['OAS'], df['Excess Return % 12-mo (Treasury)'])

des, res

(                           Variable      N      Mean        SD        SE  \
 0                               OAS   59.0  0.747618  0.099597  0.012966
 1  Excess Return % 12-mo (Treasury)   59.0  0.507072  0.251059  0.032685
 2                          combined  118.0  0.627345  0.225283  0.020739

    95% Conf.  Interval
 0   0.721663  0.773574
 1   0.441645  0.572498
 2   0.586273  0.668418  ,
                                   Independent t-test   results
 0  Difference (OAS - Excess Return % 12-mo (Treas...    0.2405
 1                              Degrees of freedom =   116.0000
 2                                               t =     6.8409
 3                           Two side test p value =     0.0000
 4                          Difference < 0 p value =     1.0000
 5                          Difference > 0 p value =     0.0000
 6                                       Cohen's d =     1.2595
 7                                       Hedge's g =     1.2513
 8                                   Glass's delta =     2.4152
 9                                               r =     0.5362)

In [18]:
des, res = researchpy.ttest(df['OAS'], df['Excess Return % 12-mo (Agg)'])

des, res

(                      Variable      N      Mean        SD        SE  \
 0                          OAS   59.0  0.747618  0.099597  0.012966
 1  Excess Return % 12-mo (Agg)   59.0  0.591016  0.233415  0.030388
 2                     combined  118.0  0.669317  0.195216  0.017971

    95% Conf.  Interval
 0   0.721663  0.773574
 1   0.530188  0.651845
 2   0.633727  0.704908  ,
                                   Independent t-test   results
 0  Difference (OAS - Excess Return % 12-mo (Agg)) =     0.1566
 1                              Degrees of freedom =   116.0000
 2                                               t =     4.7400
 3                           Two side test p value =     0.0000
 4                          Difference < 0 p value =     1.0000
 5                          Difference > 0 p value =     0.0000
 6                                       Cohen's d =     0.8727
 7                                       Hedge's g =     0.8670
 8                                   Glass's delta =     1.5724
 9                                               r =     0.4028)

In [19]:
des, res = researchpy.ttest(df['OAS'], df['Excess Return % 24-mo (Treasury)'])

des, res

(                           Variable      N      Mean        SD        SE  \
 0                               OAS   59.0  0.747618  0.099597  0.012966
 1  Excess Return % 24-mo (Treasury)   59.0  0.526237  0.215156  0.028011
 2                          combined  118.0  0.636928  0.200556  0.018463

    95% Conf.  Interval
 0   0.721663  0.773574
 1   0.470167  0.582307
 2   0.600363  0.673492  ,
                                   Independent t-test   results
 0  Difference (OAS - Excess Return % 24-mo (Treas...    0.2214
 1                              Degrees of freedom =   116.0000
 2                                               t =     7.1722
 3                           Two side test p value =     0.0000
 4                          Difference < 0 p value =     1.0000
 5                          Difference > 0 p value =     0.0000
 6                                       Cohen's d =     1.3205
 7                                       Hedge's g =     1.3120
 8                                   Glass's delta =     2.2228
 9                                               r =     0.5543)

In [20]:
des, res = researchpy.ttest(df['OAS'], df['Excess Return % 24-mo (Agg)'])

des, res

(                      Variable      N      Mean        SD        SE  \
 0                          OAS   59.0  0.747618  0.099597  0.012966
 1  Excess Return % 24-mo (Agg)   59.0  0.484175  0.235384  0.030644
 2                     combined  118.0  0.615897  0.223343  0.020560

    95% Conf.  Interval
 0   0.721663  0.773574
 1   0.422834  0.545517
 2   0.575178  0.656616  ,
                                   Independent t-test   results
 0  Difference (OAS - Excess Return % 24-mo (Agg)) =     0.2634
 1                              Degrees of freedom =   116.0000
 2                                               t =     7.9172
 3                           Two side test p value =     0.0000
 4                          Difference < 0 p value =     1.0000
 5                          Difference > 0 p value =     0.0000
 6                                       Cohen's d =     1.4577
 7                                       Hedge's g =     1.4482
 8                                   Glass's delta =     2.6451
 9                                               r =     0.5923)

In [21]:
des, res = researchpy.ttest(df['OAS'], df['Excess Return % 36-mo (Treasury)'])

des, res

(                           Variable      N      Mean        SD        SE  \
 0                               OAS   59.0  0.747618  0.099597  0.012966
 1  Excess Return % 36-mo (Treasury)   59.0  0.583539  0.211724  0.027564
 2                          combined  118.0  0.665579  0.184194  0.016956

    95% Conf.  Interval
 0   0.721663  0.773574
 1   0.528363  0.638714
 2   0.631997  0.699160  ,
                                   Independent t-test   results
 0  Difference (OAS - Excess Return % 36-mo (Treas...    0.1641
 1                              Degrees of freedom =   116.0000
 2                                               t =     5.3864
 3                           Two side test p value =     0.0000
 4                          Difference < 0 p value =     1.0000
 5                          Difference > 0 p value =     0.0000
 6                                       Cohen's d =     0.9917
 7                                       Hedge's g =     0.9853
 8                                   Glass's delta =     1.6474
 9                                               r =     0.4473)

In [22]:
des, res = researchpy.ttest(df['OAS'], df['Excess Return % 36-mo (Agg)'])

des, res

(                      Variable      N      Mean        SD        SE  \
 0                          OAS   59.0  0.747618  0.099597  0.012966
 1  Excess Return % 36-mo (Agg)   59.0  0.431933  0.189848  0.024716
 2                     combined  118.0  0.589776  0.218888  0.020150

    95% Conf.  Interval
 0   0.721663  0.773574
 1   0.382458  0.481407
 2   0.549869  0.629682  ,
                                   Independent t-test   results
 0  Difference (OAS - Excess Return % 36-mo (Agg)) =     0.3157
 1                              Degrees of freedom =   116.0000
 2                                               t =    11.3105
 3                           Two side test p value =     0.0000
 4                          Difference < 0 p value =     1.0000
 5                          Difference > 0 p value =     0.0000
 6                                       Cohen's d =     2.0824
 7                                       Hedge's g =     2.0689
 8                                   Glass's delta =     3.1696
 9                                               r =     0.7242)

# Now lets run the same t-test but with High spreads to all returns

In [23]:
df1 = pd.read_csv('minmax_OAS_with_Returns_Final_NO_Outliers_HY.csv')

In [24]:
df1.describe()

,OAS,Excess Return % 1-mo (Treasury),Excess Return % 1-mo (Agg),Excess Return % 3-mo (Treasury),Excess Return % 3-mo (Agg),Excess Return % 6-mo (Treasury),Excess Return % 6-mo (Agg),Excess Return % 9-mo (Treasury),Excess Return % 9-mo (Agg),Excess Return % 12-mo (Treasury),Excess Return % 12-mo (Agg),Excess Return % 24-mo (Treasury),Excess Return % 24-mo (Agg),Excess Return % 36-mo (Treasury),Excess Return % 36-mo (Agg)
count,279.000000,279.000000,279.000000,278.000000,278.000000,275.000000,275.000000,272.000000,272.000000,269.000000,269.000000,257.000000,257.000000,245.000000,245.000000
mean,0.351159,0.492857,0.494827,0.490379,0.489711,0.495175,0.499683,0.507613,0.505828,0.497147,0.499497,0.507319,0.498248,0.493073,0.484863
std,0.247503,0.237344,0.233785,0.235178,0.219736,0.223090,0.225057,0.219753,0.213179,0.207683,0.201386,0.215835,0.219765,0.208462,0.217124
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.155043,0.371940,0.372569,0.375000,0.375000,0.375000,0.375000,0.375000,0.375000,0.375000,0.375000,0.375000,0.375000,0.375000,0.375000
50%,0.289734,0.500462,0.504350,0.512762,0.514750,0.512260,0.523454,0.533540,0.522281,0.512685,0.503557,0.541286,0.537844,0.517038,0.523230
75%,0.489075,0.624134,0.622223,0.625000,0.625000,0.625000,0.625000,0.625000,0.625000,0.625000,0.625000,0.625000,0.625000,0.625000,0.625000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [25]:
des, res = researchpy.ttest(df['OAS'], 
            df1['Excess Return % 3-mo (Treasury)']) # notice we are using the High Spread Data for OAS

des, res

(                          Variable      N      Mean        SD        SE  \
 0                              OAS   59.0  0.747618  0.099597  0.012966
 1  Excess Return % 3-mo (Treasury)  278.0  0.490379  0.235178  0.014105
 2                         combined  337.0  0.535415  0.238525  0.012993

    95% Conf.  Interval
 0   0.721663  0.773574
 1   0.462612  0.518146
 2   0.509857  0.560974  ,
                                   Independent t-test   results
 0  Difference (OAS - Excess Return % 3-mo (Treasu...    0.2572
 1                              Degrees of freedom =   335.0000
 2                                               t =     8.2386
 3                           Two side test p value =     0.0000
 4                          Difference < 0 p value =     1.0000
 5                          Difference > 0 p value =     0.0000
 6                                       Cohen's d =     1.1809
 7                                       Hedge's g =     1.1783
 8                                   Glass's delta =     2.5828
 9                                               r =     0.4105)

In [26]:
des, res = researchpy.ttest(df['OAS'], df1['Excess Return % 3-mo (Agg)'])

des, res

(                     Variable      N      Mean        SD        SE  95% Conf.  \
 0                         OAS   59.0  0.747618  0.099597  0.012966   0.721663
 1  Excess Return % 3-mo (Agg)  278.0  0.489711  0.219736  0.013179   0.463767
 2                    combined  337.0  0.534864  0.226170  0.012320   0.510629

    Interval
 0  0.773574
 1  0.515654
 2  0.559098  ,
                                  Independent t-test   results
 0  Difference (OAS - Excess Return % 3-mo (Agg)) =     0.2579
 1                             Degrees of freedom =   335.0000
 2                                              t =     8.8173
 3                          Two side test p value =     0.0000
 4                         Difference < 0 p value =     1.0000
 5                         Difference > 0 p value =     0.0000
 6                                      Cohen's d =     1.2639
 7                                      Hedge's g =     1.2610
 8                                  Glass's delta =     2.5895
 9                                              r =     0.4340)

In [27]:
des, res = researchpy.ttest(df['OAS'], df1['Excess Return % 6-mo (Treasury)'])

des, res

(                          Variable      N      Mean        SD        SE  \
 0                              OAS   59.0  0.747618  0.099597  0.012966
 1  Excess Return % 6-mo (Treasury)  275.0  0.495175  0.223090  0.013453
 2                         combined  334.0  0.539769  0.227981  0.012475

    95% Conf.  Interval
 0   0.721663  0.773574
 1   0.468691  0.521659
 2   0.515230  0.564307  ,
                                   Independent t-test   results
 0  Difference (OAS - Excess Return % 6-mo (Treasu...    0.2524
 1                              Degrees of freedom =   332.0000
 2                                               t =     8.5040
 3                           Two side test p value =     0.0000
 4                          Difference < 0 p value =     1.0000
 5                          Difference > 0 p value =     0.0000
 6                                       Cohen's d =     1.2201
 7                                       Hedge's g =     1.2174
 8                                   Glass's delta =     2.5347
 9                                               r =     0.4229)

In [28]:
des, res = researchpy.ttest(df['OAS'], df1['Excess Return % 6-mo (Agg)'])

des, res

(                     Variable      N      Mean        SD        SE  95% Conf.  \
 0                         OAS   59.0  0.747618  0.099597  0.012966   0.721663
 1  Excess Return % 6-mo (Agg)  275.0  0.499683  0.225057  0.013571   0.472965
 2                    combined  334.0  0.543480  0.228849  0.012522   0.518847

    Interval
 0  0.773574
 1  0.526400
 2  0.568112  ,
                                  Independent t-test   results
 0  Difference (OAS - Excess Return % 6-mo (Agg)) =     0.2479
 1                             Degrees of freedom =   332.0000
 2                                              t =     8.2821
 3                          Two side test p value =     0.0000
 4                         Difference < 0 p value =     1.0000
 5                         Difference > 0 p value =     0.0000
 6                                      Cohen's d =     1.1883
 7                                      Hedge's g =     1.1856
 8                                  Glass's delta =     2.4894
 9                                              r =     0.4138)

In [29]:
des, res = researchpy.ttest(df['OAS'], df1['Excess Return % 9-mo (Treasury)'])

des, res

(                          Variable      N      Mean        SD        SE  \
 0                              OAS   59.0  0.747618  0.099597  0.012966
 1  Excess Return % 9-mo (Treasury)  272.0  0.507613  0.219753  0.013325
 2                         combined  331.0  0.550393  0.223302  0.012274

    95% Conf.  Interval
 0   0.721663  0.773574
 1   0.481380  0.533846
 2   0.526249  0.574538  ,
                                   Independent t-test   results
 0  Difference (OAS - Excess Return % 9-mo (Treasu...    0.2400
 1                              Degrees of freedom =   329.0000
 2                                               t =     8.2007
 3                           Two side test p value =     0.0000
 4                          Difference < 0 p value =     1.0000
 5                          Difference > 0 p value =     0.0000
 6                                       Cohen's d =     1.1778
 7                                       Hedge's g =     1.1751
 8                                   Glass's delta =     2.4098
 9                                               r =     0.4120)

In [30]:
des, res = researchpy.ttest(df['OAS'], df1['Excess Return % 9-mo (Agg)'])

des, res

(                     Variable      N      Mean        SD        SE  95% Conf.  \
 0                         OAS   59.0  0.747618  0.099597  0.012966   0.721663
 1  Excess Return % 9-mo (Agg)  272.0  0.505828  0.213179  0.012926   0.480380
 2                    combined  331.0  0.548927  0.218295  0.011999   0.525323

    Interval
 0  0.773574
 1  0.531276
 2  0.572530  ,
                                  Independent t-test   results
 0  Difference (OAS - Excess Return % 9-mo (Agg)) =     0.2418
 1                             Degrees of freedom =   329.0000
 2                                              t =     8.5053
 3                          Two side test p value =     0.0000
 4                         Difference < 0 p value =     1.0000
 5                         Difference > 0 p value =     0.0000
 6                                      Cohen's d =     1.2215
 7                                      Hedge's g =     1.2187
 8                                  Glass's delta =     2.4277
 9                                              r =     0.4246)

In [31]:
des, res = researchpy.ttest(df['OAS'], df1['Excess Return % 12-mo (Treasury)'])

des, res

(                           Variable      N      Mean        SD        SE  \
 0                               OAS   59.0  0.747618  0.099597  0.012966
 1  Excess Return % 12-mo (Treasury)  269.0  0.497147  0.207683  0.012663
 2                          combined  328.0  0.542201  0.215389  0.011893

    95% Conf.  Interval
 0   0.721663  0.773574
 1   0.472216  0.522078
 2   0.518805  0.565598  ,
                                   Independent t-test   results
 0  Difference (OAS - Excess Return % 12-mo (Treas...    0.2505
 1                              Degrees of freedom =   326.0000
 2                                               t =     9.0306
 3                           Two side test p value =     0.0000
 4                          Difference < 0 p value =     1.0000
 5                          Difference > 0 p value =     0.0000
 6                                       Cohen's d =     1.2982
 7                                       Hedge's g =     1.2952
 8                                   Glass's delta =     2.5149
 9                                               r =     0.4473)

In [32]:
des, res = researchpy.ttest(df['OAS'], df1['Excess Return % 12-mo (Agg)'])

des, res

(                      Variable      N      Mean        SD        SE  \
 0                          OAS   59.0  0.747618  0.099597  0.012966
 1  Excess Return % 12-mo (Agg)  269.0  0.499497  0.201386  0.012279
 2                     combined  328.0  0.544128  0.210019  0.011596

    95% Conf.  Interval
 0   0.721663  0.773574
 1   0.475322  0.523672
 2   0.521315  0.566941  ,
                                   Independent t-test   results
 0  Difference (OAS - Excess Return % 12-mo (Agg)) =     0.2481
 1                              Degrees of freedom =   326.0000
 2                                               t =     9.2118
 3                           Two side test p value =     0.0000
 4                          Difference < 0 p value =     1.0000
 5                          Difference > 0 p value =     0.0000
 6                                       Cohen's d =     1.3243
 7                                       Hedge's g =     1.3212
 8                                   Glass's delta =     2.4913
 9                                               r =     0.4545)

In [33]:
des, res = researchpy.ttest(df['OAS'], df1['Excess Return % 24-mo (Treasury)'])

des, res

(                           Variable      N      Mean        SD        SE  \
 0                               OAS   59.0  0.747618  0.099597  0.012966
 1  Excess Return % 24-mo (Treasury)  257.0  0.507319  0.215835  0.013463
 2                          combined  316.0  0.552185  0.220187  0.012386

    95% Conf.  Interval
 0   0.721663  0.773574
 1   0.480806  0.533832
 2   0.527814  0.576556  ,
                                   Independent t-test   results
 0  Difference (OAS - Excess Return % 24-mo (Treas...    0.2403
 1                              Degrees of freedom =   314.0000
 2                                               t =     8.3424
 3                           Two side test p value =     0.0000
 4                          Difference < 0 p value =     1.0000
 5                          Difference > 0 p value =     0.0000
 6                                       Cohen's d =     1.2043
 7                                       Hedge's g =     1.2014
 8                                   Glass's delta =     2.4127
 9                                               r =     0.4259)

In [34]:
des, res = researchpy.ttest(df['OAS'], df1['Excess Return % 24-mo (Agg)'])

des, res

(                      Variable      N      Mean        SD        SE  \
 0                          OAS   59.0  0.747618  0.099597  0.012966
 1  Excess Return % 24-mo (Agg)  257.0  0.498248  0.219765  0.013709
 2                     combined  316.0  0.544808  0.224833  0.012648

    95% Conf.  Interval
 0   0.721663  0.773574
 1   0.471252  0.525244
 2   0.519923  0.569693  ,
                                   Independent t-test   results
 0  Difference (OAS - Excess Return % 24-mo (Agg)) =     0.2494
 1                              Degrees of freedom =   314.0000
 2                                               t =     8.5095
 3                           Two side test p value =     0.0000
 4                          Difference < 0 p value =     1.0000
 5                          Difference > 0 p value =     0.0000
 6                                       Cohen's d =     1.2284
 7                                       Hedge's g =     1.2255
 8                                   Glass's delta =     2.5038
 9                                               r =     0.4329)

In [35]:
des, res = researchpy.ttest(df['OAS'], df1['Excess Return % 36-mo (Treasury)'])

des, res

(                           Variable      N      Mean        SD        SE  \
 0                               OAS   59.0  0.747618  0.099597  0.012966
 1  Excess Return % 36-mo (Treasury)  245.0  0.493073  0.208462  0.013318
 2                          combined  304.0  0.542475  0.216936  0.012442

    95% Conf.  Interval
 0   0.721663  0.773574
 1   0.466840  0.519306
 2   0.517991  0.566959  ,
                                   Independent t-test   results
 0  Difference (OAS - Excess Return % 36-mo (Treas...    0.2545
 1                              Degrees of freedom =   302.0000
 2                                               t =     9.1232
 3                           Two side test p value =     0.0000
 4                          Difference < 0 p value =     1.0000
 5                          Difference > 0 p value =     0.0000
 6                                       Cohen's d =     1.3230
 7                                       Hedge's g =     1.3198
 8                                   Glass's delta =     2.5558
 9                                               r =     0.4648)

In [36]:
des, res = researchpy.ttest(df['OAS'], df1['Excess Return % 36-mo (Agg)'])

des, res

(                      Variable      N      Mean        SD        SE  \
 0                          OAS   59.0  0.747618  0.099597  0.012966
 1  Excess Return % 36-mo (Agg)  245.0  0.484863  0.217124  0.013872
 2                     combined  304.0  0.535858  0.225158  0.012914

    95% Conf.  Interval
 0   0.721663  0.773574
 1   0.457540  0.512186
 2   0.510446  0.561270  ,
                                   Independent t-test   results
 0  Difference (OAS - Excess Return % 36-mo (Agg)) =     0.2628
 1                              Degrees of freedom =   302.0000
 2                                               t =     9.0600
 3                           Two side test p value =     0.0000
 4                          Difference < 0 p value =     1.0000
 5                          Difference > 0 p value =     0.0000
 6                                       Cohen's d =     1.3139
 7                                       Hedge's g =     1.3106
 8                                   Glass's delta =     2.6382
 9                                               r =     0.4623)