In [1]:
import pandas as pd
import csv
import numpy as np
import seaborn as sns
sns.set_palette('husl')
import matplotlib.pyplot as plt
%matplotlib inline
%pylab inline

Populating the interactive namespace from numpy and matplotlib

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
df = pd.read_excel('Multi_Sector_ETF_extGL_analysis_AGG.xlsx') 
df.head()

,Date,ETF Name - AGG,Portfolio Return - AGG,"Average Return [3, 6, 9] - AGG","Volatility, short - AGG","Volatility, med - AGG","Volatility, long - AGG",ETF Name - LBU,Portfolio Return - LBU,"Average Return [3, 6, 9] - LBU","Volatility, short - LBU","Volatility, med - LBU","Volatility, long - LBU"
0,2015-01-01,AGG,2.05231,2.729735,0.202,0.179,0.167,LBU,2.09698,2.601183,0.176,0.164,0.160
1,2015-02-01,AGG,-0.89468,4.272149,0.209,0.188,0.177,LBU,-0.940213,4.206490,0.175,0.173,0.167
2,2015-03-01,AGG,0.375289,2.319376,0.240,0.208,0.193,LBU,0.464449,2.219713,0.218,0.195,0.180
3,2015-04-01,AGG,-0.323636,2.884690,0.267,0.236,0.211,LBU,-0.65899,2.879042,0.239,0.209,0.191
4,2015-05-01,AGG,-0.436819,1.598650,0.249,0.232,0.211,LBU,-0.240751,1.263064,0.222,0.203,0.192

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66 entries, 0 to 65
Data columns (total 13 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Date                            66 non-null     datetime64[ns]
 1   ETF Name - AGG                  66 non-null     object
 2   Portfolio Return - AGG          66 non-null     object
 3   Average Return [3, 6, 9] - AGG  66 non-null     float64
 4   Volatility, short - AGG         66 non-null     float64
 5   Volatility, med - AGG           66 non-null     float64
 6   Volatility, long - AGG          66 non-null     float64
 7   ETF Name - LBU                  66 non-null     object
 8   Portfolio Return - LBU          66 non-null     object
 9   Average Return [3, 6, 9] - LBU  66 non-null     float64
 10  Volatility, short - LBU         66 non-null     float64
 11  Volatility, med - LBU           66 non-null     float64
 12  Volatility, long - LBU          66 non-null     float64
dtypes: datetime64[ns](1), float64(8), object(4)
memory usage: 6.8+ KB

In [5]:
df.describe()

,"Average Return [3, 6, 9] - AGG","Volatility, short - AGG","Volatility, med - AGG","Volatility, long - AGG","Average Return [3, 6, 9] - LBU","Volatility, short - LBU","Volatility, med - LBU","Volatility, long - LBU"
count,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000
mean,1.775268,0.228682,0.216621,0.210303,1.710988,0.210545,0.205091,0.202030
std,2.303323,0.174258,0.116425,0.091906,2.209135,0.073192,0.049640,0.040249
min,-2.151567,0.129000,0.140000,0.149000,-1.960142,0.147000,0.151000,0.158000
25%,-0.231086,0.168250,0.164250,0.165250,-0.322675,0.172750,0.174000,0.176250
50%,1.621767,0.187500,0.186000,0.191500,1.519529,0.196500,0.194500,0.197000
75%,3.694860,0.217750,0.223500,0.212000,3.596978,0.221500,0.219500,0.211750
max,7.788943,1.011000,0.730000,0.612000,7.001722,0.516000,0.396000,0.352000

# We need to create new data points from our prev. data.
## We want to create ratios for the trailing volatility.
### We want to do our security volatility  / benchmark volatility for short, medium, and long trailing volatilities.
### Long Vol. = 9 month, Med. Vol. = 6 month, Short = 3 month

#### Example below:
$$ Long Volatility Ratio = \frac{Long Volatitly TLT}{Long Volatiltiy LBU} $$

In [8]:
df["Long Volatility Ratio"] = df["Volatility, long - AGG"] / df["Volatility, long - LBU"] 
df["Medium Volatility Ratio"] = df["Volatility, med - AGG"] / df["Volatility, med - LBU"]
df["Short Volatility Ratio"] = df["Volatility, short - AGG"] / df["Volatility, short - LBU"]

In [9]:
df.head()

,Date,ETF Name - AGG,Portfolio Return - AGG,"Average Return [3, 6, 9] - AGG","Volatility, short - AGG","Volatility, med - AGG","Volatility, long - AGG",ETF Name - LBU,Portfolio Return - LBU,"Average Return [3, 6, 9] - LBU","Volatility, short - LBU","Volatility, med - LBU","Volatility, long - LBU",Long Volatility Ratio,Medium Volatility Ratio,Short Volatility Ratio
0,2015-01-01,AGG,2.05231,2.729735,0.202,0.179,0.167,LBU,2.09698,2.601183,0.176,0.164,0.160,1.043750,1.091463,1.147727
1,2015-02-01,AGG,-0.89468,4.272149,0.209,0.188,0.177,LBU,-0.940213,4.206490,0.175,0.173,0.167,1.059880,1.086705,1.194286
2,2015-03-01,AGG,0.375289,2.319376,0.240,0.208,0.193,LBU,0.464449,2.219713,0.218,0.195,0.180,1.072222,1.066667,1.100917
3,2015-04-01,AGG,-0.323636,2.884690,0.267,0.236,0.211,LBU,-0.65899,2.879042,0.239,0.209,0.191,1.104712,1.129187,1.117155
4,2015-05-01,AGG,-0.436819,1.598650,0.249,0.232,0.211,LBU,-0.240751,1.263064,0.222,0.203,0.192,1.098958,1.142857,1.121622

# Now we need to create a Differential return dataframe
## Example Below:

$$ Differential Return TLT = (Portfolio Return - AGG) -  (Portfolio Return - LBU) $$

In [15]:
# We have to convert the returns to float64, for some reason they were labeled as Objects
df["Differential Return"] = pd.to_numeric(df['Portfolio Return - AGG'],errors='coerce') - pd.to_numeric(df['Portfolio Return - LBU'],errors='coerce')

In [16]:
df.head()

,Date,ETF Name - AGG,Portfolio Return - AGG,"Average Return [3, 6, 9] - AGG","Volatility, short - AGG","Volatility, med - AGG","Volatility, long - AGG",ETF Name - LBU,Portfolio Return - LBU,"Average Return [3, 6, 9] - LBU","Volatility, short - LBU","Volatility, med - LBU","Volatility, long - LBU",Long Volatility Ratio,Medium Volatility Ratio,Short Volatility Ratio,Differential Return
0,2015-01-01,AGG,2.05231,2.729735,0.202,0.179,0.167,LBU,2.09698,2.601183,0.176,0.164,0.160,1.043750,1.091463,1.147727,-0.044674
1,2015-02-01,AGG,-0.89468,4.272149,0.209,0.188,0.177,LBU,-0.940213,4.206490,0.175,0.173,0.167,1.059880,1.086705,1.194286,0.045534
2,2015-03-01,AGG,0.375289,2.319376,0.240,0.208,0.193,LBU,0.464449,2.219713,0.218,0.195,0.180,1.072222,1.066667,1.100917,-0.089160
3,2015-04-01,AGG,-0.323636,2.884690,0.267,0.236,0.211,LBU,-0.65899,2.879042,0.239,0.209,0.191,1.104712,1.129187,1.117155,0.335354
4,2015-05-01,AGG,-0.436819,1.598650,0.249,0.232,0.211,LBU,-0.240751,1.263064,0.222,0.203,0.192,1.098958,1.142857,1.121622,-0.196068